### ISSUE TITLE
Question about 'alpha' in evaluate_gpu.py

### ISSUE THREAD

**Issue by TTTREE** [NVlabs/DG-Net#10]
Thanks for your code. I have learned the paper and the code. I can't understand the role of 'alpha' in  evaluate_gpu.py.
like this :
" alpha = [0, 0.5, -1]"
“if alpha[j] == -1:
        qf[0:512] *= 0”
Would you please explain it for me？Why are u doing this?
Thank u.

**Comment by layumi** [comment]
`alpha = 0` only evaluate the `f_prime`; 
`alpha = -1` only evaluate the  `f_fine`;
 `alpha = 0.5` is the result that combines `f_prime` with `f_fine`

**Comment by TTTREE** [comment]
Thanks for your quick reply!!
