### ISSUE TITLE
Supplementary of paper

### ISSUE THREAD

**Issue by CuongNguyen218** [NVlabs/DG-Net#15]
Hi authors,
I have read your papers and have some question about architecture details. But I can't find supplementary material in this paper. Can you give me more detail or supplementary material 
Thanks you.

**Comment by layumi** [comment]
Hi @CuongNguyen218 ,

We attached the supplementary in the end of the paper (after the reference).

**Comment by xiaodongyang** [comment]
Check out the supplementary material here http://xiaodongyang.org/publications/papers/dgnet-supp-cvpr19.pdf

**Comment by CuongNguyen218** [comment]
Thanks you
