### ISSUE TITLE
Network structure

### ISSUE THREAD

**Issue by CuongNguyen218** [NVlabs/DG-Net#16]
Hi @layumi ,
I was a bit confuse when read your code. I can't find appearance encoder and discriminator like your describe in your paper in your code. are they style encoder and MsImageDis in networks.py right ?

**Comment by layumi** [comment]
Hi @CuongNguyen218 

Thank you. 
`appearance encoder` is the `self.id_a` in the `trainer.py`, which is a ResNet-50 model defined in the `reIDmodel.py` called `ft_netAB `. Note that the appearance encoder is also applied to conduct the discriminative learning (person reID learning).

Yes. `discriminator` is the `self.dis_a` in the `trainer.py`, which is defined by `MsImageDis ` in the `networks.py`.

**Comment by CuongNguyen218** [comment]
Thanks for your help but I have a question about network architecture. Why did you choose different network structures for different purpose like extract appearance encoder, structure encoder and discriminator.

**Comment by layumi** [comment]
@CuongNguyen218 
The main idea is as follows:
`appearance encoder` is to encoder the high-level semantic information for person re-ID. ResNet-50 is the most common choice in the previous works;
`structure encoder` is to reconstruct the image, so we want a relatively high-resolution structure that could preserve the details of the image, especially the spatial information. So we use a shallow network with 2 or 3 `stride=2`;
`discriminator` is follow `munit` and `drit` to use three networks for different-scale inputs.

**Comment by CuongNguyen218** [comment]
I got it. Thanks you so much.
