### ISSUE TITLE
data sets generated with DG-net

### ISSUE THREAD

**Issue by 2110317008** [NVlabs/DG-Net#20]
Can you still provide duke, MSMT, CUHK03 data sets generated with DG-net?Thank you!

**Comment by layumi** [comment]
First of all, thank you for your interest in our work.

Due to the original dataset license, we may not have the right to release the generated data. I will discuss with @xiaodongyang @Chrisding  and check the license issue again.

Thanks a lot @2110317008

**Comment by 2110317008** [comment]
Thank you for your prompt reply! Looking forward to a good result! Thank you!
