### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by LilySys** [NVlabs/DG-Net#21]
Hi, when i use your model to start evaluation,  i got this error as follow:
          Traceback (most recent call last):
            File "fid.py", line 23, in <module>
              import tensorflow as tf
          ModuleNotFoundError: No module named 'tensorflow'
when i activated tensorflow env, and i run the code, i got this error as follow:
            ModuleNotFoundError: No module named 'torch'
i don't know how to solve the problem.Can you give me some suggestions to solve the problem?Thank you.

**Comment by layumi** [comment]
Hi @LilySys 
Sorry. I did not make it clear.
For image generation, you should have pytorch.
For FID calculation, you should have tensorflow.

If you do not have an environment that includes both pytorch and tensorflow, I suggest you to run the code except the last line with pytorch, and then enable tensorflow to run the last command.

https://github.com/NVlabs/DG-Net/blob/master/visual_tools/test_folder.py#L151

**Comment by LilySys** [comment]
thank you very much, according to your method , the problem has been solved the problem.
