### ISSUE TITLE
Regarding Transfer Learning from market to duke

### ISSUE THREAD

**Issue by asthaverma13** [NVlabs/DG-Net#23]
Can you please give the setting for transfer learning in a more detailed manner?
How we have to use the code for transfer learning?

**Comment by layumi** [comment]
Hi @asthaverma13 
You could directly use the model that we trained on Market to evaluate on other datasets, e.g., Duke and MSMT. The output should be close to the result at https://github.com/NVlabs/DG-Net#person-re-id-evaluation

**Comment by asthaverma13** [comment]
Thanks a lot.
