### ISSUE TITLE
Generate my own image?

### ISSUE THREAD

**Issue by kayakaracakaya** [NVlabs/DG-Net#25]
Firstly, thanks for the work and sorry for my low knowledge.

I want to give two specific image, source and target, and transfer pose of source to target. How can i do this, can you explain to me step by step?

Thanks.

**Comment by layumi** [comment]
Hi  @kayakaracakaya 
Thanks for your attention on our papers. 
You mentioned that you want to transfer the pose of the source to target. 
Do you want to preserve the identity of the source image or target image? 

If you would like to generate the Fig. 5 or Fig.9 in the paper, you may check

`visual_tools/show_smooth.py` generates Figure 5 of the paper.

`visual_tools/show_smooth_structure.py` generates Figure 9 of the paper.

For DG-Net, we focus on the changing appearance of the foreground object, i.e., the cloth of the person.
So it is not optimal for changing the pose.

For changing pose, I recommend several papers as follows. You may refer to them. Hope them could help you.

[1] Wei L, Zhang S, Gao W, et al. Person transfer gan to bridge domain gap for person re-identification CVPR 2018
[2] https://github.com/charliememory/Pose-Guided-Person-Image-Generation
