### ISSUE TITLE
What does "off_gan_bg1" and "off_gan_id1"mean in visual_data/test_folder.py?

### ISSUE THREAD

**Issue by sherlockedlee** [NVlabs/DG-Net#29]
I'm new to Re-ID,what should I do if I want to use the generated images to do data augmentation in other algorithms?And if I want to use show_smooth.py,how can I get samples in input_folder" visual_data"?Thank u a lot for your brilliant work.  @layumi

**Comment by layumi** [comment]
Hi, @sherlockedlee 
`off_gan_bg1` and `off_gan_id1` are two folders with generated images but with different file organization.
One folder is to keep the background but change the appearance code in every sub-folder; the other is to keep the appearance code but change the background code in every sub-folder.
