### ISSUE TITLE
Multiple GPU Training

### ISSUE THREAD

**Issue by Phi-C** [NVlabs/DG-Net#3]
we want to train the model on 4 GPUS:
python train.py --name latest --config configs/latest.yaml --gpu_ids 0,1,2,3
But the RuntimeError "CUDA out of memory"  occurs, it seems only one GPU is used.
Any help?
Thank you.

**Comment by layumi** [comment]
Hi @ChenXingjian ,
Thank you for your attention to our paper. 
We left some api for multiple GPUs but we do not use it. For the time being, we do not support the multiple GPU training. We will consider to add it to the next version.

**Comment by tau-yihouxiang** [comment]
I checked that torch.nn.DataParallel has been used. Why doesn't multi-gpu model work?

**Comment by layumi** [comment]
You may check the code at:
https://github.com/NVlabs/DG-Net/issues/5

We are still working on how to parallel the adaptive instance normalization layer.
