### ISSUE TITLE
How is it made sure that the image returned from train_loader_a and train_loader_b is of different identity?

### ISSUE THREAD

**Issue by chaitrasj** [NVlabs/DG-Net#42]
Hello,
Thank you for this so modular, easy to understand code.
I have a doubt, as far as i can understand, you are trying to sample images using train_loader_a and train_loader_b, such that images_a and pos_a are of same id, similarly images_b and pos_b are of same id, but images_a and images_b are different id.. Am i correct?
If this is the case, where has the constraint been put that these 2 loaders at run time must load images of different identity? Also there is a method _get_neg_sample in class ReIDFolder. I thought that would be getting used somehow, but I cannot see anywhere that method getting used.
Please help me if i am going wrong anywhere. Your reply would be highly appreciated.

Thanks,
Chaitra

**Comment by layumi** [comment]
Hi @chaitrasj 
Yes. You are right.  I did not write this part. 
However, it does not affect the final result, since it is low probability to have two dataloaders return images of the same identity.
