### ISSUE TITLE
Interpreting the results of the score in evaluate_gpu.py

### ISSUE THREAD

**Issue by ksuhartono97** [NVlabs/DG-Net#48]
Hi, I am trying to understand what is the range of the score that comes out from the `evaluate` function

Putting the function here as reference

```
def evaluate(qf,ql,qc,gf,gl,gc):
    query = qf.view(-1,1)
    score = torch.mm(gf,query)
    score = score.squeeze(1).cpu()
    score = score.numpy()
    
    .....
```

I expected the scores to be in a range from 0 to 1, but it seems that the results here show values that can go negative and beyond 1. Is this expected behaviour? If yes, what is the score range as I would like to normalize these values.

**Comment by layumi** [comment]
Hi @ksuhartono97 

For the cosine similarity, the score is in [-1,1].  

For this repo, I normalize and then concatenate the two features at 
https://github.com/NVlabs/DG-Net/blob/master/reid_eval/test_2label.py#L137-L138

So the value of score is [-2,2]. You may have a try.

**Comment by ksuhartono97** [comment]
I see thanks!
