### ISSUE TITLE
Can you share the trained models on the dataset MSMT17 and the dataset MSMT17?

### ISSUE THREAD

**Issue by Be-yourself-zxy** [NVlabs/DG-Net#52]
When i train the models on the MSMT17,the following error occurred:
Traceback (most recent call last):
  File "test_2label.py", line 205, in <module>
    gallery_feature = extract_feature(model,dataloaders['gallery'])
  File "test_2label.py", line 132, in extract_feature
    x[0] = norm(x[0])
  File "test_2label.py", line 110, in norm
    fnorm = torch.norm(f, p=2, dim=1, keepdim=True)
  File "/home/lei/.local/lib/python3.6/site-packages/torch/functional.py", line 705, in norm
    return torch._C._VariableFunctions.norm(input, p, dim, keepdim=keepdim)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
How can i modify the preparation and evaluation code of the dataset MSMT17？Could you give me some suggwstions? Thank you !

**Comment by layumi** [comment]
You may send the request to my email. Due to the dataset license, we can not directly share it.

**Comment by RuriApoka** [comment]
> When i train the models on the MSMT17,the following error occurred:
> Traceback (most recent call last):
> File "test_2label.py", line 205, in
> gallery_feature = extract_feature(model,dataloaders['gallery'])
> File "test_2label.py", line 132, in extract_feature
> x[0] = norm(x[0])
> File "test_2label.py", line 110, in norm
> fnorm = torch.norm(f, p=2, dim=1, keepdim=True)
> File "/home/lei/.local/lib/python3.6/site-packages/torch/functional.py", line 705, in norm
> return torch._C._VariableFunctions.norm(input, p, dim, keepdim=keepdim)
> IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
> How can i modify the preparation and evaluation code of the dataset MSMT17？Could you give me some suggwstions? Thank you !

@Be-yourself-zxy Hello, I meet the same problem. Did you solve it? Thank you.
