### ISSUE TITLE
Question about alpha

### ISSUE THREAD

**Issue by exityan** [NVlabs/DG-Net#54]
Hi, 

Thank you for your work.

In `reid_eval/evaluate_gpu.py`, you are giving a weight to `f_prime` and `f_fine` of query features with `alpha` value.
But I'm curious why you are not giving an weight to gallery features.

Is there any reason you are not doing so?

Thank you!

**Comment by layumi** [comment]
Hi @exityan 
Thank you. It is due to the cosine similarity metric. If we add alpha to both query and gallery, the multiplication result will obtain a weight of `alpha^2`
