### ISSUE TITLE
issue with 'net_last.pth'

### ISSUE THREAD

**Issue by khodabakhshih** [NVlabs/DG-Net#58]
Hi
Thanks for your great work. I use the pre-trained model for feature extraction using function “extract_feature” in the file “test2_label.py”.
There is no problem with ‘.pt’ models in the “outputs” folder, but when I want to use the ‘net_last.pth’ model in folder “model” I receive the following error:
KeyError                                  Traceback (most recent call last)
<ipython-input-6-9d1a429451cf> in <module>()
KeyError: 'a'
Would you please guide me to debug this error? Is it about the “config.yaml” file exists in folder “outputs” and does not exist in folder “model”?
Thank you very much and looking forward to hearing you
Regards
Hossein

**Comment by khodabakhshih** [comment]
I think it is about line 91 in file "test2_label.py"
 network.load_state_dict(state_dict['a'], strict=False)
the '.pt' files has 'a' and '.pth' has not. Therefore for '.pth' files we should use:
 network.load_state_dict(state_dict, strict=False)

**Comment by khodabakhshih** [comment]
another question:
what '.yaml' file should be use for '.pth' files?
why the cosine distance of feature vectors using '.pth' files are near 1 while it is nice for '.pt' files?

**Comment by layumi** [comment]
Hi @khodabakhshih 
I wrote many different structure choices for our model structure.

So we need to load `yaml` config files to get the right model structure first. 

Then we can load the weight into the model structure.

**Comment by layumi** [comment]
```
-- models # contain the teacher models
-- outputs # contain the final DG-Net models
```

**Comment by khodabakhshih** [comment]
@layumi Thank you very much.
