### ISSUE TITLE
如何采用训练好的模型去生成图片

### ISSUE THREAD

**Issue by SeibertronSS** [NVlabs/DG-Net#65]
您好，我和我的同事对您的工作十分感兴趣。现在我们遇到了一个问题，我们想要采用您训练好的模型去生成更多的图像，但是我们无法读入您训练好的模型参数。事实上，我们在构建好DG-NET之后，无法读取您在网盘中存入的net_last.pth文件，模型与参数是不匹配的。请问您知道是什么原因吗？

**Comment by layumi** [comment]
@SeibertronSS 
您能提供具体的报错 log么？
