### ISSUE TITLE
in trainer.py /gen_update(),  i cannot understand "encoder is tuned, input is fixed" and "encoder is fixed, input is tuned"

### ISSUE THREAD

**Issue by wdf19961118** [NVlabs/DG-Net#67]

**Comment by layumi** [comment]
Hi @wdf19961118 
It is a two-stage strategy. If you are familiar with EM (Expectation Maximization Algorithm), the mechanism is somehow similar. 
We can not update input and encoder at the same time, which may lead to the optimisation problems such as overfitting.
