### ISSUE TITLE
One question about generating images

### ISSUE THREAD

**Issue by muzishen** [NVlabs/DG-Net#7]
Hello, can you tell me if you have only implemented the change of appearance space, but not the transformation of structure space. For example, to generate a visual Angle image that does not exist in the structure space. Thank u

**Comment by layumi** [comment]
Hi @muzishen 

Thank you for your question.
Do you mean how to interpolate the generated results on the structure space?
You may modify the `/visual_tools/show_smooth.py` a little bit, and replace the appearance code with the structure code.

**Comment by muzishen** [comment]
Thank you very much for your quick reply!  This paper addresses the interchange problem of appearance space. I want to know if this code can do structure space interchange. What I mean by that is that I'm referring to the structure of A to get the same structure of B. How I modify it if it can.

**Comment by layumi** [comment]
Hi @muzishen 
Sorry for the late response. I will upload the code soon.

**Comment by layumi** [comment]
I have uploaded the code. You may refer to the `visual_tools/show_smooth_structure.py`.

The main code is at this line:
https://github.com/NVlabs/DG-Net/blob/master/visual_tools/show_smooth_structure.py#L119
