### ISSUE TITLE
test_folder

### ISSUE THREAD

**Issue by bixiaopeng0** [NVlabs/DG-Net#70]
`                im.save(dst_path + '/%03d_%03d_gan%s.jpg'%(label2, label, name[:-4]))
                im.save(dst_path2 + '/%03d_%03d_gan%s.jpg'%(label2, label, name[:-4]))`
请问为什么在两个输出目录，保存了相同的图片呀，是bug吗

**Comment by layumi** [comment]
https://github.com/NVlabs/DG-Net/blob/master/visual_tools/test_folder.py#L140-L141
One folder saves the generated image according to id embedding, while another folder saves the same image according to the background embedding.
