### ISSUE TITLE
关于inception score

### ISSUE THREAD

**Issue by zichihuanian** [NVlabs/DG-Net#73]
作者你好，我想请问你在计算inception score的时候，使用的inception net是在market上训练过的，还是单纯使用imagenet预训练的模型？

**Comment by layumi** [comment]
你好。采用的是 imagenet pretrained 模型。

**Comment by qinghe-sun** [comment]
> 你好。采用的是 imagenet pretrained 模型。

好的，谢谢大佬。
我还想问下使用imagenet pretrained model 会不会不客观，毕竟re-id的图片和imagenet差别还是挺大的。
我是看stack gan做生成任务时，使用了在对应的数据集（CUB等）预训练过后的模型来计算IS，才有这样的疑问，望解惑，十分感谢！
