### ISSUE TITLE
关于FID计算

### ISSUE THREAD

**Issue by zichihuanian** [NVlabs/DG-Net#74]
你好，请问FID计算使用的是全部的真实图片数据集（train+test）和生成的约12000张图片之间的FID吗？还是也挑选12000张真实图片进行比较？

**Comment by layumi** [comment]
你好。是和所有 train 数据比较的。 

所有train 和 生成的。（图像数量不需要完全一样）

测试代码在 https://github.com/NVlabs/DG-Net/blob/master/visual_tools/test_folder.py#L151

**Comment by zichihuanian** [comment]
> 你好。是和所有 train 数据比较的。
> 
> 所有train 和 生成的。（图像数量不需要完全一样）
> 
> 测试代码在 https://github.com/NVlabs/DG-Net/blob/master/visual_tools/test_folder.py#L151

谢谢大佬，我看paper中有个ground truth（表中的Real）的FID，若是两个一模一样的数据集，结果应该为0呀？请问这里你是计算的哪两个数据集之间的FID？

**Comment by layumi** [comment]
你好 @qinghe-sun 
我有点忘记了。当时 好像是用 train_all 和 gallery 互相测的 / 或者把train_all 分了两个部分。这样能反应一定的问题。
FID也不是0.

**Comment by zichihuanian** [comment]
好的，谢谢啦！
