### ISSUE TITLE
appearance code and structure code

### ISSUE THREAD

**Issue by Wooks-git** [NVlabs/DG-Net#77]
Thank you for present your code.
I have a question about appearance code and structure code in your paper.
you wrote in the networks.py style and content encoder. Is it appearance encoder and structre encoder respectively?

**Comment by layumi** [comment]
@Wooks-git 
Thank you. Yes.

**Comment by Wooks-git** [comment]
@layumi Thank you for fast reply. I have one more question. can i ask this page? or make another issue?
why do you use two dataloader(train_loader_a and train_loader_b)?
