### ISSUE TITLE
test_2label报错 yaml.load()缺少 loader 

### ISSUE THREAD

**Issue by taqta** [NVlabs/DG-Net#79]
大佬， test_2label.py 里面的
with open(config_path, 'r') as stream:
     config = yaml.load(stream)
会报错，说缺少参数loader

**Comment by layumi** [comment]
感谢！ 是因为最新的 pyyaml 加了一项。 

可以试试添加  yaml.load(stream, loader=yaml.Loader)

或者使用 yaml.safe_load(stream)

我更新了相关代码。

**Comment by taqta** [comment]
好的，谢谢大佬
