### ISSUE TITLE
question about gan type

### ISSUE THREAD

**Issue by NotQualified** [NVlabs/DG-Net#8]
I notice that your network code support nsgan and wgan additionally, but I can't run nsgan (maybe because of apex, I'm not sure) straightly and it seems that wgan part is not fully functional. So have you ever tried to use nsgan or wgan to train? And how did it work? Thank you!

**Comment by layumi** [comment]
Hi @NotQualified 

Thank you.
We only used the lsgan in our paper. I will fix other gan functions recently. 
Thanks a lot.

**Comment by layumi** [comment]
Hi @NotQualified 
I just updated the `wgan` and `nsgan` in the `network.py`. You may check out it.
Note that `wgan` needs a large regularisation term. I suggest to set `Lambda=0.1`
For `lsgan` and `nsgan`, you may still use `Lambda=0.01`.
