### ISSUE TITLE
basic information about predict_label

### ISSUE THREAD

**Issue by Adorablepet** [NVlabs/DG-Net#9]
Thanks for you sharing codes. I have a question, I can not find opt.alpha in ` trainer.py` about predict_label function. `opt` seems not to be defined. Could you explain it?

**Comment by layumi** [comment]
Hi @Adorablepet ,

`alpha` is `B_W` in the config files. I will make it more clear.

**Comment by layumi** [comment]
Hi @Adorablepet 

The alpha is used to updated the teacher model (temporal ensemble), which have not been used in our paper.
This idea is from https://arxiv.org/abs/1703.01780 
However, we did not use it in the final version. I will update it soon.

**Comment by Adorablepet** [comment]
@layumi thanks, I know, you are a good man.
